/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\components\qr.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/qr.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['Rectangle_-_Stroke'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 0]} />
        <mesh geometry={nodes['Rectangle_-_Stroke_1'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 1]} />
        <mesh geometry={nodes['Rectangle_-_Stroke_2'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 2]} />
        <mesh geometry={nodes['Path_-_Stroke'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 3]} />
        <mesh geometry={nodes['Path_-_Stroke_1'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 4]} />
        <mesh geometry={nodes['Path_-_Stroke_2'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 5]} />
        <mesh geometry={nodes['Path_-_Stroke_3'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 6]} />
        <mesh geometry={nodes['Path_-_Stroke_4'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 7]} />
        <mesh geometry={nodes['Path_-_Stroke_5'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 8]} />
        <mesh geometry={nodes['Path_-_Stroke_6'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 9]} />
        <mesh geometry={nodes['Path_-_Stroke_7'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 10]} />
        <mesh geometry={nodes['Path_-_Stroke_8'].geometry} material={materials['Acrylic Glass']} position={[-0.216, 0, 11]} />
      </group>
    </group>
  )
}

useGLTF.preload('/qr.glb')
